services:
  app:
    container_name: thanhdev-fe-device-pulse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:
    external: true
